version: "2.2"
services:
  gitlab:
    image: 'gitlab/gitlab-ce:11.10.1-ce.0'
    restart: always
    hostname: 'localhost'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost'
    ports:
      - '10080:80'
      - '10443:443'
      - '10022:22'
    volumes:
      - './srv/gitlab/logs:/var/log/gitlab'
      - './srv/gitlab/config:/etc/gitlab'
      - './srv/gitlab/data:/var/opt/gitlab'